"""Writers that persist compiled artifacts to disk."""

from __future__ import annotations

import ast
import json
import os
import time
from dataclasses import dataclass
from pathlib import Path

from .jsx_imports import rewrite_pyxl_import_specifiers
from .linemap import build_line_map, compress_to_spans, render_debug_footer
from .model import ActionDeclaration, CompilationResult, ImageDeclaration, PageMetadata, ScriptDeclaration
from .parser import PyxParseResult

#: Aggregate sidecar in the client build root mapping each generated ``.jsx``
#: to its ``.pyxl`` origin and per-line source lines. Consumed by the inline
#: Vite plugin in the generated ``vite.config.js`` (dev only) to emit source
#: maps that let browser devtools and js-debug show and bind ``.pyxl`` files.
CLIENT_SOURCEMAP_SIDECAR = "pyxl-sourcemaps.json"

_STATIC_STUB = '"""Generated by Pyxle for a static page."""\n'
_JSX_STUB = "// Generated by Pyxle: no client component provided.\n"
_SERVER_IMPORT = "from pyxle.runtime import server"
_ACTION_IMPORT = "from pyxle.runtime import action"
_SERVER_ACTION_IMPORT = "from pyxle.runtime import server, action"
_ACTION_ERROR_IMPORT = "from pyxle.runtime import ActionError"
_VALIDATION_ACTION_ERROR_IMPORT = "from pyxle.runtime import ValidationActionError"
_LOADER_ERROR_IMPORT = "from pyxle.runtime import LoaderError"
_INVALIDATE_ROUTES_IMPORT = "from pyxle.runtime import invalidate_routes"


@dataclass
class ArtifactWriter:
    build_root: Path
    client_root: Path
    server_root: Path
    metadata_root: Path

    def write(
        self,
        source_path: Path,
        page_relative_path: Path,
        route_path: str,
        alternate_route_paths: tuple[str, ...] | None,
        parse_result: PyxParseResult,
    ) -> CompilationResult:
        server_rel = Path("pages") / page_relative_path.with_suffix(".py")
        client_rel = Path("pages") / page_relative_path.with_suffix(".jsx")
        metadata_rel = Path("pages") / page_relative_path.with_suffix(".json")

        server_output = self.server_root / server_rel
        client_output = self.client_root / client_rel
        metadata_output = self.metadata_root / metadata_rel

        server_output.parent.mkdir(parents=True, exist_ok=True)
        client_output.parent.mkdir(parents=True, exist_ok=True)
        metadata_output.parent.mkdir(parents=True, exist_ok=True)

        python_code = (
            parse_result.python_code
            if parse_result.python_code.strip()
            else _STATIC_STUB
        )
        has_loader = bool(parse_result.loader)
        has_actions = bool(parse_result.actions)
        if has_loader and has_actions and python_code.strip():
            python_code = ensure_server_action_import(python_code)
        elif has_loader and python_code.strip():
            python_code = ensure_server_import(python_code)
        elif has_actions and python_code.strip():
            python_code = ensure_action_import(python_code)
        # Any page that declares at least one @action gets ``ActionError``
        # auto-imported too. Otherwise, the very first time a handler
        # tries ``raise ActionError(...)`` it fails with a bewildering
        # ``NameError: name 'ActionError' is not defined`` — the single
        # most common surprise in early Pyxle apps.
        if has_actions and python_code.strip():
            python_code = ensure_action_error_import(python_code)
            python_code = ensure_validation_action_error_import(python_code)
            # ``invalidate_routes`` is the action-side helper that evicts a
            # route's cached navigation payload after a mutation — inject it
            # alongside ``ActionError`` for the same no-surprise reason.
            python_code = ensure_invalidate_routes_import(python_code)
        # A ``@server`` loader raises ``LoaderError`` to trigger the nearest
        # ``error.pyxl`` boundary, exactly as an ``@action`` raises
        # ``ActionError`` — so auto-import it for parity. Without this, the first
        # ``raise LoaderError(...)`` fails with a bewildering NameError even
        # though the equivalent action pattern works out of the box.
        if has_loader and python_code.strip():
            python_code = ensure_loader_error_import(python_code)
        jsx_code = (
            parse_result.jsx_code
            if parse_result.jsx_code.strip()
            else _JSX_STUB
        )
        jsx_code, _ = rewrite_pyxl_import_specifiers(jsx_code)

        # Debug footer: persist the emitted-line → .pyxl-line map inside the
        # generated module itself, so the map is atomically in sync with the
        # code it describes. The dev server's importer (debug mode) uses it to
        # exec the module as its .pyxl — .pyxl tracebacks and native debugger
        # breakpoints. Static stubs carry no user Python and get no footer.
        if parse_result.python_code.strip():
            line_map = build_line_map(
                parse_result.python_code,
                parse_result.python_line_numbers,
                python_code,
            )
            spans = compress_to_spans(line_map)
            if spans:
                source_rel = _relative_posix(source_path, server_output.parent)
                python_code += render_debug_footer(source_rel, spans)

        # The client source-map sidecar must land BEFORE the .jsx below: Vite
        # invalidates and may re-transform the module the instant the .jsx is
        # rewritten, and a map read at that moment must already be the new one.
        if parse_result.jsx_code.strip():
            self._update_client_sourcemap_sidecar(
                client_rel=client_rel,
                source_path=source_path,
                jsx_line_numbers=parse_result.jsx_line_numbers,
            )
        else:
            # A page that dropped all its JSX still writes a 1-line stub .jsx, so
            # reconcile (which only prunes entries whose .jsx is gone) keeps a
            # now-stale entry whose map references generated lines that no longer
            # exist. Remove it here.
            self._remove_client_sourcemap_sidecar_entry(client_rel)

        server_output.write_text(python_code, encoding="utf-8")
        client_output.write_text(jsx_code, encoding="utf-8")

        # Convert script/image declarations from dicts to dataclass instances
        def to_bool(value):
            """Coerce an extracted JSX attribute value to a boolean.

            Babel hands us real booleans for ``defer`` / ``defer={true}`` and
            strings for quoted forms (``defer="false"``). A bare/expression
            ``true`` is True; an explicit falsy string (``"false"``, ``"0"``,
            ``"no"``, ``"off"``, ``""``) is False; any other present value is
            True (HTML-attribute-presence semantics).
            """
            if isinstance(value, bool):
                return value
            if isinstance(value, str):
                return value.strip().lower() not in ("", "false", "0", "no", "off")
            return False

        scripts = tuple(
            ScriptDeclaration(
                src=s.get("src", ""),
                strategy=s.get("strategy", "afterInteractive"),
                async_=to_bool(s.get("async")),
                defer=to_bool(s.get("defer")),
                module=to_bool(s.get("module")),
                no_module=to_bool(s.get("noModule")),
            )
            for s in parse_result.script_declarations
        )
        images = tuple(
            ImageDeclaration(
                src=i.get("src", ""),
                width=int(i.get("width", 0)) if i.get("width") else None,
                height=int(i.get("height", 0)) if i.get("height") else None,
                alt=i.get("alt", ""),
                priority=to_bool(i.get("priority")),
                lazy=to_bool(i.get("lazy", True)),  # Default to True if not specified
            )
            for i in parse_result.image_declarations
        )

        actions = tuple(
            ActionDeclaration(name=a.name, line=a.line_number)
            for a in parse_result.actions
        )

        metadata = PageMetadata(
            route_path=route_path,
            alternate_route_paths=tuple(alternate_route_paths or ()),
            client_path="/" + client_rel.as_posix(),
            server_path="/" + server_rel.as_posix(),
            loader_name=parse_result.loader.name if parse_result.loader else None,
            loader_line=parse_result.loader.line_number if parse_result.loader else None,
            head_elements=parse_result.head_elements,
            head_is_dynamic=parse_result.head_is_dynamic,
            scripts=scripts,
            images=images,
            head_jsx_blocks=parse_result.head_jsx_blocks,
            actions=actions,
            websocket_name=(
                parse_result.websocket.name if parse_result.websocket else None
            ),
            websocket_line=(
                parse_result.websocket.line_number
                if parse_result.websocket
                else None
            ),
            cache_revalidate=parse_result.cache_revalidate,
            standalone=parse_result.standalone,
            uses_suspense=parse_result.uses_suspense,
        )

        metadata_output.write_text(
            json.dumps(metadata.to_json(), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

        return CompilationResult(
            source_path=source_path,
            python_code=python_code,
            jsx_code=jsx_code,
            server_output=server_output,
            client_output=client_output,
            metadata_output=metadata_output,
            metadata=metadata,
        )

    def _update_client_sourcemap_sidecar(
        self,
        *,
        client_rel: Path,
        source_path: Path,
        jsx_line_numbers: tuple[int, ...],
    ) -> None:
        """Record this page's ``.jsx`` → ``.pyxl`` line map in the sidecar.

        The sidecar aggregates every page (keyed by client-root-relative
        ``.jsx`` path); build passes are serialised by the builder, so a plain
        read-modify-replace is race-free. Paths are stored relative to the
        client root — no absolute paths in build artifacts.
        """
        sidecar_path = self.client_root / CLIENT_SOURCEMAP_SIDECAR
        try:
            entries = json.loads(sidecar_path.read_text(encoding="utf-8"))
            if not isinstance(entries, dict):
                entries = {}
        except (OSError, json.JSONDecodeError):
            entries = {}
        entries[client_rel.as_posix()] = {
            "pyxl": _relative_posix(source_path, self.client_root),
            "lines": list(jsx_line_numbers),
        }
        self.client_root.mkdir(parents=True, exist_ok=True)
        _atomic_write_replace(
            sidecar_path, json.dumps(entries, indent=2, sort_keys=True) + "\n"
        )

    def _remove_client_sourcemap_sidecar_entry(self, client_rel: Path) -> None:
        """Drop a page's sidecar entry when it no longer has a client component."""
        sidecar_path = self.client_root / CLIENT_SOURCEMAP_SIDECAR
        try:
            entries = json.loads(sidecar_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return
        if not isinstance(entries, dict):
            return
        if entries.pop(client_rel.as_posix(), None) is not None:
            _atomic_write_replace(
                sidecar_path, json.dumps(entries, indent=2, sort_keys=True) + "\n"
            )


def reconcile_client_sourcemap_sidecar(client_root: Path) -> None:
    """Drop sidecar entries whose generated ``.jsx`` no longer exists.

    Called once at the end of a build pass so ``pyxl-sourcemaps.json`` mirrors
    the live set of client modules — a deleted page never leaves a stale entry
    pointing at a removed ``.pyxl``. Cheap (one ``stat`` per entry) and
    idempotent; a missing or unreadable sidecar is a no-op.
    """
    sidecar_path = client_root / CLIENT_SOURCEMAP_SIDECAR
    try:
        entries = json.loads(sidecar_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return
    if not isinstance(entries, dict):
        return
    live = {
        key: value
        for key, value in entries.items()
        if (client_root / key).is_file()
    }
    if len(live) == len(entries):
        return
    _atomic_write_replace(
        sidecar_path, json.dumps(live, indent=2, sort_keys=True) + "\n"
    )


def _relative_posix(target: Path, base: Path) -> str:
    """``target`` relative to ``base`` as a POSIX path (``..`` hops allowed).

    On Windows, :func:`os.path.relpath` raises ``ValueError`` when ``target``
    and ``base`` live on different drives (e.g. the project on ``C:`` and the
    build dir on ``D:``). A relative path is then impossible, so fall back to an
    absolute POSIX path — the debug loader resolves ``<module dir> / <this>``
    and an absolute right-hand side wins, and the client source-map plugin
    resolves it the same way — rather than crashing the compile.
    """
    try:
        return Path(os.path.relpath(target, base)).as_posix()
    except ValueError:
        return target.resolve().as_posix()


def _atomic_write_replace(target: Path, text: str) -> None:
    """Write *text* to *target* atomically, tolerating Windows lock contention.

    Writes a sibling temp file then ``os.replace``s it into place. On Windows
    ``os.replace`` raises ``PermissionError`` when the target is momentarily
    open by another process (Vite reading the sidecar during a hot-reload
    burst); retry a few times with a short backoff before giving up.
    """
    tmp_path = target.with_suffix(target.suffix + ".tmp")
    tmp_path.write_text(text, encoding="utf-8")
    for attempt in range(5):
        try:
            tmp_path.replace(target)
            return
        except PermissionError:  # pragma: no cover - Windows-only timing
            if attempt == 4:
                tmp_path.unlink(missing_ok=True)
                raise
            time.sleep(0.05 * (attempt + 1))


def ensure_action_import(source: str) -> str:
    """Ensure ``from pyxle.runtime import action`` is present in *source*."""
    if not source.strip():
        return source

    try:
        module = ast.parse(source, mode="exec", type_comments=True)
    except SyntaxError:  # pragma: no cover - defensive fallback
        module = None

    if module is not None and not _needs_action_import(module):
        return source

    lines = source.splitlines()
    insert_at = _determine_server_import_index(lines, module)
    lines.insert(insert_at, _ACTION_IMPORT)
    result = "\n".join(lines)
    if source.endswith("\n"):
        result += "\n"
    return result


def ensure_server_action_import(source: str) -> str:
    """Ensure both ``server`` and ``action`` are imported from ``pyxle.runtime``."""
    if not source.strip():
        return source

    try:
        module = ast.parse(source, mode="exec", type_comments=True)
    except SyntaxError:  # pragma: no cover - defensive fallback
        module = None

    needs_server = module is None or _needs_server_import(module)
    needs_action = module is None or _needs_action_import(module)

    if not needs_server and not needs_action:
        return source

    # If one already exists but not the other, insert the missing one individually.
    if needs_server and not needs_action:
        return ensure_server_import(source)
    if needs_action and not needs_server:
        return ensure_action_import(source)

    # Both missing — emit a combined import.
    lines = source.splitlines()
    insert_at = _determine_server_import_index(lines, module)
    lines.insert(insert_at, _SERVER_ACTION_IMPORT)
    result = "\n".join(lines)
    if source.endswith("\n"):
        result += "\n"
    return result


def ensure_server_import(source: str, *, return_insert_position: bool = False) -> str | tuple[str, int | None]:
    if not source.strip():
        return (source, None) if return_insert_position else source

    try:
        module = ast.parse(source, mode="exec", type_comments=True)
    except SyntaxError:  # pragma: no cover - defensive fallback
        module = None

    if module is not None and not _needs_server_import(module):
        return (source, None) if return_insert_position else source

    lines = source.splitlines()
    insert_at = _determine_server_import_index(lines, module)
    lines.insert(insert_at, _SERVER_IMPORT)

    result = "\n".join(lines)
    if source.endswith("\n"):
        result += "\n"
    if return_insert_position:
        return result, insert_at
    return result


def _needs_server_import(module: ast.Module) -> bool:
    for node in module.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == "server":
            return False
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "server":
                    return False
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.target.id == "server":
            return False
        if isinstance(node, ast.ImportFrom):
            for alias in node.names:
                if alias.asname == "server" or (alias.asname is None and alias.name == "server"):
                    return False
        if isinstance(node, ast.Import):
            for alias in node.names:
                name = alias.asname or alias.name.split(".")[-1]
                if name == "server":
                    return False
    return True


def _needs_action_import(module: ast.Module) -> bool:
    for node in module.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == "action":
            return False
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "action":
                    return False
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.target.id == "action":
            return False
        if isinstance(node, ast.ImportFrom):
            for alias in node.names:
                if alias.asname == "action" or (alias.asname is None and alias.name == "action"):
                    return False
        if isinstance(node, ast.Import):
            for alias in node.names:
                name = alias.asname or alias.name.split(".")[-1]
                if name == "action":
                    return False
    return True


def ensure_action_error_import(source: str) -> str:
    """Ensure ``from pyxle.runtime import ActionError`` is present.

    Called whenever the source has at least one ``@action`` so the
    idiomatic ``raise ActionError(...)`` pattern works without the user
    writing an import. A user who already imports ``ActionError`` (by
    that name or via an alias, module-level attribute, or as a
    local class) is detected and the helper is a no-op.
    """
    return _ensure_runtime_name_import(source, "ActionError", _ACTION_ERROR_IMPORT)


def ensure_validation_action_error_import(source: str) -> str:
    """Ensure ``from pyxle.runtime import ValidationActionError`` is present.

    Mirror of :func:`ensure_action_error_import` for the validation
    subclass, which a handler raises by hand for checks Pydantic can't
    express (uniqueness, cross-field rules). Auto-imported independently
    of ``ActionError`` — a user-defined name still takes precedence.
    """
    return _ensure_runtime_name_import(
        source, "ValidationActionError", _VALIDATION_ACTION_ERROR_IMPORT
    )


def ensure_loader_error_import(source: str) -> str:
    """Ensure ``from pyxle.runtime import LoaderError`` is present.

    Called whenever the source declares a ``@server`` loader, so the idiomatic
    ``raise LoaderError(...)`` pattern — which renders the nearest ``error.pyxl``
    boundary — works without a manual import. Parity with
    :func:`ensure_action_error_import`. A user who already owns the name is
    detected and this is a no-op.
    """
    return _ensure_runtime_name_import(source, "LoaderError", _LOADER_ERROR_IMPORT)


def ensure_invalidate_routes_import(source: str) -> str:
    """Ensure ``from pyxle.runtime import invalidate_routes`` is present.

    Auto-imported for pages with at least one ``@action`` — the helper that
    evicts a route's cached navigation payload after a mutation. A user-defined
    name still takes precedence.
    """
    return _ensure_runtime_name_import(
        source, "invalidate_routes", _INVALIDATE_ROUTES_IMPORT
    )


def _ensure_runtime_name_import(source: str, name: str, import_line: str) -> str:
    """Inject ``import_line`` unless ``name`` is already defined/imported."""
    if not source.strip():
        return source

    try:
        module = ast.parse(source, mode="exec", type_comments=True)
    except SyntaxError:  # pragma: no cover - defensive fallback
        module = None

    if module is not None and not _needs_runtime_name(module, name):
        return source

    lines = source.splitlines()
    insert_at = _determine_server_import_index(lines, module)
    lines.insert(insert_at, import_line)
    result = "\n".join(lines)
    if source.endswith("\n"):
        result += "\n"
    return result


def _needs_runtime_name(module: ast.Module, name: str) -> bool:
    """Whether ``name`` is undefined at module scope (so it needs importing).

    Mirror of :func:`_needs_action_import`: a local def/class, a module-level
    assignment, or an existing import of ``name`` (by name or alias) all count
    as the user owning the name, and suppress auto-injection.
    """
    for node in module.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == name:
            return False
        if isinstance(node, ast.ClassDef) and node.name == name:
            return False
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == name:
                    return False
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.target.id == name:
            return False
        if isinstance(node, ast.ImportFrom):
            for alias in node.names:
                if alias.asname == name or (
                    alias.asname is None and alias.name == name
                ):
                    return False
        if isinstance(node, ast.Import):
            for alias in node.names:
                imported = alias.asname or alias.name.split(".")[-1]
                if imported == name:
                    return False
    return True


def _determine_server_import_index(lines: list[str], module: ast.Module | None) -> int:
    if not lines:
        return 0

    line_after_prelude = _line_after_docstring_and_future(module)
    if line_after_prelude is not None:
        return min(max(line_after_prelude, 0), len(lines))

    index = 0
    while index < len(lines) and not lines[index].strip():
        index += 1
    return index


def _line_after_docstring_and_future(module: ast.Module | None) -> int | None:
    if module is None or not module.body:
        return None

    insert_line = 0
    body_index = 0

    first_stmt = module.body[0]
    if _is_module_docstring(first_stmt):
        insert_line = first_stmt.end_lineno or first_stmt.lineno
        body_index = 1

    while body_index < len(module.body):
        node = module.body[body_index]
        if isinstance(node, ast.ImportFrom) and node.module == "__future__":
            insert_line = node.end_lineno or node.lineno
            body_index += 1
            continue
        break

    if insert_line == 0:
        return None
    return insert_line


def _is_module_docstring(node: ast.stmt) -> bool:
    return (
        isinstance(node, ast.Expr)
        and isinstance(node.value, ast.Constant)
        and isinstance(node.value.value, str)
        and node.col_offset == 0
    )
